
= package domain



== Interfaces

=== GitRepositoryStore
[source, go]
----
type GitRepositoryStore interface {
    FetchGitRepositories() ([]*GitRepository, error)
    Clone(repository *GitRepository) error
    Checkout(repository *GitRepository) error
    Fetch(repository *GitRepository) error
    Reset(repository *GitRepository) error
    Pull(repository *GitRepository) error
    Add(repository *GitRepository) error
    Commit(repository *GitRepository, options CommitOptions) error
    Diff(repository *GitRepository) (string, error)
    Push(repository *GitRepository, options PushOptions) error
}
----

GitRepositoryStore provides methods to interact with GitRepository on the local filesystem.
Most methods described follow the corresponding Git operations.

In Domain-Driven Design language, the term `Store` corresponds to `Repository`, but to avoid name clash it was named `Store`.

.FetchGitRepositories
[source, go]
----
func FetchGitRepositories() ([]*GitRepository, error)
----
FetchGitRepositories loads a list of GitRepository from a configuration set.
Returns an empty list on first error.

.Clone
[source, go]
----
func Clone(repository *GitRepository) error
----
Clone will download the given GitRepository to local filesystem.
The location is specified in GitRepository.RootDir.

.Checkout
[source, go]
----
func Checkout(repository *GitRepository) error
----
Checkout checks out the GitRepository.CommitBranch.

.Fetch
[source, go]
----
func Fetch(repository *GitRepository) error
----
Fetch retrieves the objects and refs from remote.

.Reset
[source, go]
----
func Reset(repository *GitRepository) error
----
Reset current HEAD to GitRepository.CommitBranch.

.Pull
[source, go]
----
func Pull(repository *GitRepository) error
----
Pull integrates objects from remote.

.Add
[source, go]
----
func Add(repository *GitRepository) error
----
Add stages all files in GitRepository.RootDir.

.Commit
[source, go]
----
func Commit(repository *GitRepository, options CommitOptions) error
----
Commit records changes in the repository.

.Diff
[source, go]
----
func Diff(repository *GitRepository) (string, error)
----
Diff returns a `patch`-compatible diff between HEAD and previous commit as string.
The diff may be empty.

.Push
[source, go]
----
func Push(repository *GitRepository, options PushOptions) error
----
Push updates remote refs.

'''

=== LabelStore
[source, go]
----
type LabelStore interface {
    FetchLabelsForRepository(url *GitURL) (LabelSet, error)
    EnsureLabelsForRepository(url *GitURL, labels LabelSet) error
    RemoveLabelsFromRepository(url *GitURL, labels LabelSet) error
}
----

LabelStore provides methods to interact with labels on a Git hosting service.

In Domain-Driven Design language, the term `Store` corresponds to `Repository`, but to avoid name clash it was named `Store`.

.FetchLabelsForRepository
[source, go]
----
func FetchLabelsForRepository(url *GitURL) (LabelSet, error)
----
FetchLabelsForRepository retrieves a LabelSet for the given repository.

.EnsureLabelsForRepository
[source, go]
----
func EnsureLabelsForRepository(url *GitURL, labels LabelSet) error
----
EnsureLabelsForRepository creates or updates the given LabelSet in the given repository.
Labels that exist remotely, but not in the given LabelSet are ignored.
Remote labels have to be updated when Label.GetColor or Label.Description are not matching.

Renaming labels are currently not supported.

.RemoveLabelsFromRepository
[source, go]
----
func RemoveLabelsFromRepository(url *GitURL, labels LabelSet) error
----
RemoveLabelsFromRepository remotely removes all labels in the given LabelSet.
Only the Label.Name is relevant to determine label equality.

'''

=== PullRequestStore
[source, go]
----
type PullRequestStore interface {
    FindMatchingPullRequest(repository *GitRepository) (*PullRequest, error)
    EnsurePullRequest(repository *GitRepository) error
}
----

PullRequestStore provides methods to interact with PullRequest on a Git hosting service.

In Domain-Driven Design language, the term `Store` corresponds to `Repository`, but to avoid name clash it was named `Store`.

.FindMatchingPullRequest
[source, go]
----
func FindMatchingPullRequest(repository *GitRepository) (*PullRequest, error)
----
FindMatchingPullRequest returns the PullRequest that has the same branch as GitRepository.CommitBranch.
If not found, it returns nil without error.

.EnsurePullRequest
[source, go]
----
func EnsurePullRequest(repository *GitRepository) error
----
EnsurePullRequest creates or updates the GitRepository.PullRequest in the repository.

 * This operation does not alter any properties of existing labels.
 * Existing labels are left untouched, but any extraneous labels are removed.
 * Title and Body are updated.
 * Existing Commit and Base branches are left untouched.

The first error encountered aborts the operation.

'''

=== RenderServiceInstrumentationFactory
[source, go]
----
type RenderServiceInstrumentationFactory interface {
    NewRenderServiceInstrumentation(repository *GitRepository) RenderServiceInstrumentation
}
----

RenderServiceInstrumentationFactory provides factory methods to create new instances.

.NewRenderServiceInstrumentation
[source, go]
----
func NewRenderServiceInstrumentation(repository *GitRepository) RenderServiceInstrumentation
----
NewRenderServiceInstrumentation creates a new RenderServiceInstrumentation instance using the given GitRepository as context.

'''

=== RenderServiceInstrumentation
[source, go]
----
type RenderServiceInstrumentation interface {
    FetchedTemplatesFromStore(fetchErr error) error
    FetchedValuesForTemplate(fetchErr error, template *Template) error
    AttemptingToRenderTemplate(template *Template)
    WrittenRenderResultToFile(template *Template, targetPath Path, writeErr error) error
}
----

RenderServiceInstrumentation provides methods for domain observability.

.FetchedTemplatesFromStore
[source, go]
----
func FetchedTemplatesFromStore(fetchErr error) error
----
FetchedTemplatesFromStore logs a message indicating that fetching templates from TemplateStore was successful, but only if fetchErr is nil.
Returns fetchErr unmodified for method chaining.

.FetchedValuesForTemplate
[source, go]
----
func FetchedValuesForTemplate(fetchErr error, template *Template) error
----
FetchedValuesForTemplate logs a message indicating that fetching Values from ValueStore was successful but only if fetchErr is nil.
Returns fetchErr unmodified for method chaining.

.AttemptingToRenderTemplate
[source, go]
----
func AttemptingToRenderTemplate(template *Template)
----
AttemptingToRenderTemplate logs a message indicating that the actual rendering is about to begin.

.WrittenRenderResultToFile
[source, go]
----
func WrittenRenderResultToFile(template *Template, targetPath Path, writeErr error) error
----


'''

=== TemplateEngine
[source, go]
----
type TemplateEngine interface {
    Execute(template *Template, values Values) (RenderResult, error)
}
----

TemplateEngine provides methods to process a Template.

.Execute
[source, go]
----
func Execute(template *Template, values Values) (RenderResult, error)
----
Execute renders the given Template with the given Values.

'''

=== TemplateStore
[source, go]
----
type TemplateStore interface {
    FetchTemplates() ([]*Template, error)
}
----

TemplateStore provides methods to load Template from template root directory.

In Domain-Driven Design language, the term `Store` corresponds to `Repository`, but to avoid name clash it was named `Store`.

.FetchTemplates
[source, go]
----
func FetchTemplates() ([]*Template, error)
----
FetchTemplates lists all templates.
It aborts on first error.

'''

=== ValueStore
[source, go]
----
type ValueStore interface {
    FetchValuesForTemplate(template *Template, repository *GitRepository) (Values, error)
    FetchUnmanagedFlag(template *Template, repository *GitRepository) (bool, error)
    FetchTargetPath(template *Template, repository *GitRepository) (Path, error)
    FetchFilesToDelete(repository *GitRepository) ([]Path, error)
}
----

ValueStore provides methods to query Values from a configuration.

In Domain-Driven Design language, the term `Store` corresponds to `Repository`, but to avoid name clash it was named `Store`.

.FetchValuesForTemplate
[source, go]
----
func FetchValuesForTemplate(template *Template, repository *GitRepository) (Values, error)
----
FetchValuesForTemplate retrieves the Values for the given template.

.FetchUnmanagedFlag
[source, go]
----
func FetchUnmanagedFlag(template *Template, repository *GitRepository) (bool, error)
----
FetchUnmanagedFlag returns true if the given template should not be rendered.
The implementation may return ErrKeyNotFound if the flag is undefined, as the boolean 'false' is ambiguous.

.FetchTargetPath
[source, go]
----
func FetchTargetPath(template *Template, repository *GitRepository) (Path, error)
----
FetchTargetPath returns an alternative output path for the given template relative to the Git repository.
An empty string indicates that there is no alternative path configured.

.FetchFilesToDelete
[source, go]
----
func FetchFilesToDelete(repository *GitRepository) ([]Path, error)
----
FetchFilesToDelete returns a slice of Path that should be deleted in the Git repository.
The paths are relative to the Git root directory.

'''


== Structs

=== CleanupService
[source, go]
----
type CleanupService struct {
}
----





**Receivers**

.CleanupUnwantedFiles
[source, go]
----
func (s *CleanupService) CleanupUnwantedFiles(ctx CleanupContext) error
----




'''

=== CleanupContext
[source, go]
----
type CleanupContext struct {
    Repository    *GitRepository
    ValueStore    ValueStore
}
----










**Receivers**


'''

=== GitRepository
[source, go]
----
type GitRepository struct {
    RootDir          Path
    URL              *GitURL
    PullRequest      *PullRequest
    Labels           LabelSet
    CommitBranch     string
    DefaultBranch    string
}
----

GitRepository is the heart of the domain.

The model itself doesn't feature common actions like Commit.
It was decided against adding those rich functionalities since that would mean implementing a replayable history of actions to keep in memory.
This was considered too complicated, thus these actions are to be implemented in Stores.

RootDir::
RootDir is the full path to the Git root directory in the local filesystem.

URL::
URL is the remote URL of origin.

PullRequest::
PullRequest is the associated PullRequest for this repository in the remote Git hosting service.

Labels::
Labels contains the LabelSet that is present in the remote Git hosting service.

CommitBranch::
CommitBranch in the branch name of the current branch the working tree is in.

DefaultBranch::
DefaultBranch is the branch name of the remote default branch (usually `master` or `main`).



**Receivers**

.SetLabels
[source, go]
----
func (r *GitRepository) SetLabels(labels LabelSet) error
----

SetLabels validates and sets the new LabelSet.
Returns nil if there are no empty Label names or duplicates.


'''

=== CommitOptions
[source, go]
----
type CommitOptions struct {
    Message    string
    Amend      bool
}
----

CommitOptions contains settings to influence the GitRepositoryStore.Commit action.

Message::
Message contains the commit message.

Amend::
Amend will edit the last commit instead of creating a new one.




'''

=== PushOptions
[source, go]
----
type PushOptions struct {
    Force    bool
}
----

PushOptions contains settings to influence the GitRepositoryStore.Push action.

Force::
Force overwrites the remote state when pushing.




'''

=== Label
[source, go]
----
type Label struct {
    Name           string
    Description    string
}
----

Label is a Value object containing the properties of labels in a Git hosting service.

Name::
Name is the label name

Description::
Description adds additional details to the label.




**Receivers**

.GetColor
[source, go]
----
func (l Label) GetColor() Color
----

GetColor returns the color of the Label.

.SetColor
[source, go]
----
func (l *Label) SetColor(color Color) error
----

SetColor sets the color of the Label.
If Color.CheckValue fails, then that error is returned.

.IsSameAs
[source, go]
----
func (l Label) IsSameAs(label Label) bool
----

IsSameAs returns true if each Label.Name is equal.

.IsEqualTo
[source, go]
----
func (l Label) IsEqualTo(label Label) bool
----

IsEqualTo returns true if all properties of Label are equal.


'''

=== PullRequest
[source, go]
----
type PullRequest struct {
    CommitBranch    string
    BaseBranch      string
}
----

PullRequest is a model that represents a pull request in a remote Git hosting service.




CommitBranch::
CommitBranch is the branch name of the current working tree.

BaseBranch::
BaseBranch is the branch name into which CommitBranch should be merged into.




**Receivers**

.GetLabels
[source, go]
----
func (pr *PullRequest) GetLabels() LabelSet
----

GetLabels returns the LabelSet of this PR.

.SetNumber
[source, go]
----
func (pr *PullRequest) SetNumber(nr *PullRequestNumber) error
----

SetNumber sets the pull request number.

.GetNumber
[source, go]
----
func (pr *PullRequest) GetNumber() *PullRequestNumber
----

GetNumber returns the pull request number.
It returns nil if this PullRequest does not yet exist in remote.

.GetTitle
[source, go]
----
func (pr *PullRequest) GetTitle() string
----

GetTitle returns the PR title.

.GetBody
[source, go]
----
func (pr *PullRequest) GetBody() string
----

GetBody returns the PR description.

.ChangeDescription
[source, go]
----
func (pr *PullRequest) ChangeDescription(title, body string) error
----

ChangeDescription changes the title and body of this PR.
An error is returned if the title is empty.

.AttachLabels
[source, go]
----
func (pr *PullRequest) AttachLabels(labels LabelSet) error
----

AttachLabels sets the LabelSet of this PR.
There cannot be duplicates or labels with no name.


'''

=== RenderService
[source, go]
----
type RenderService struct {
}
----

RenderService is a domain service that helps rendering templates.




**Receivers**

.RenderTemplates
[source, go]
----
func (s *RenderService) RenderTemplates(ctx RenderContext) error
----

RenderTemplates loads the Templates and renders them in the GitRepository.RootDir of the given RenderContext.Repository.


'''

=== RenderContext
[source, go]
----
type RenderContext struct {
    Repository       *GitRepository
    ValueStore       ValueStore
    TemplateStore    TemplateStore
    Engine           TemplateEngine
}
----

RenderContext represents a single rendering context for a GitRepository.














**Receivers**


'''

=== Template
[source, go]
----
type Template struct {
    RelativePath       Path
    FilePermissions    Permissions
}
----

Template is a reference to a file that contains special syntax.

RelativePath::
RelativePath is the Path reference to where the template file is contained within the template root directory.

FilePermissions::
FilePermissions defines what file permissions this template file has.
Rendered files should have the same permissions as template files.



**Receivers**

.Render
[source, go]
----
func (t *Template) Render(values Values, engine TemplateEngine) (RenderResult, error)
----

Render takes the given Values and returns a RenderResult from the given TemplateEngine.


'''


== Variable Typedefinitions

=== Color
[source, go]
----
type Color string
----

Color is a 6-digit uppercase hexadecimal string value with '#' prefix

**Receivers**

.String
[source, go]
----
func (c Color) String() string
----

String returns the color in hexadecimal RGB format

.CheckValue
[source, go]
----
func (c Color) CheckValue() error
----

CheckValue returns ErrInvalidArgument in case the string is not in an acceptable format.
Returns nil otherwise.


'''

=== LabelSet
[source, go]
----
type LabelSet []Label
----

LabelSet is a set of Label.

**Receivers**

.CheckForEmptyLabelNames
[source, go]
----
func (s LabelSet) CheckForEmptyLabelNames() error
----

CheckForEmptyLabelNames returns an error if there's a Label in the set that is an empty string.

.CheckForDuplicates
[source, go]
----
func (s LabelSet) CheckForDuplicates() error
----

CheckForDuplicates returns an error if two or more Label have the same Label.Name.

.FindLabelByName
[source, go]
----
func (s LabelSet) FindLabelByName(label string) (Label, bool)
----

FindLabelByName returns the Label by given Name, if there is one matching.

.Merge
[source, go]
----
func (s LabelSet) Merge(other LabelSet) LabelSet
----

Merge returns a new copy of LabelSet that contains the Label from other if they are missing in the original slice, and replaces existing ones.
A label to replace is determined by equality of LabelSet.FindLabelByName.

No validation checks are performed.
The original order is not preserved.
Duplicates are removed from the result.

.Without
[source, go]
----
func (s LabelSet) Without(other LabelSet) LabelSet
----

Without returns a new LabelSet that contain only the labels that do not exist in other set.
A label is not included in the result if the name matches.

No validation checks are performed.
The original order is preserved.


'''

=== Path
[source, go]
----
type Path string
----

Path is a Value object identifying a file path.

**Receivers**

.Exists
[source, go]
----
func (p Path) Exists() bool
----

Exists returns true if the path exists in the local file system.

.FileExists
[source, go]
----
func (p Path) FileExists() bool
----

FileExists returns true if the path exists in the local file system and is a file.

.DirExists
[source, go]
----
func (p Path) DirExists() bool
----

DirExists returns true if the path exists in the local file system and is a directory.

.Join
[source, go]
----
func (p Path) Join(elems ...Path) Path
----

Join takes this Path as root and makes a new Path with given elements.

.Delete
[source, go]
----
func (p Path) Delete()
----

Delete removes the path (and possibly all children if it's a directory), ignoring any errors.
If you need error handling, use os.RemoveAll directly.

.String
[source, go]
----
func (p Path) String() string
----

String returns a string representation of itself.


'''

=== PullRequestNumber
[source, go]
----
type PullRequestNumber int
----

PullRequestNumber identifies a PullRequest by a number in a Git hosting service.

**Receivers**

.String
[source, go]
----
func (nr PullRequestNumber) String() string
----

String returns the number prefixed with `#`.

.Int
[source, go]
----
func (nr *PullRequestNumber) Int() *int
----

Int returns nil if nr is also nil.
Otherwise, it returns an int pointer.


'''

=== RenderResult
[source, go]
----
type RenderResult string
----

RenderResult represents the string value after rendering from a Template.

**Receivers**

.WriteToFile
[source, go]
----
func (r RenderResult) WriteToFile(path Path, permissions Permissions) error
----

WriteToFile writes the content to the given Path with given Permissions.
Otherwise, an error is returned.


'''

=== Permissions
[source, go]
----
type Permissions fs.FileMode
----

Permissions is an alias for file permissions.

**Receivers**

.FileMode
[source, go]
----
func (p Permissions) FileMode() fs.FileMode
----

FileMode converts Permissions to fs.FileMode.


'''

=== GitURL
[source, go]
----
type GitURL url.URL
----

GitURL is the same as url.URL but with additional helper methods.

**Receivers**

.GetRepositoryName
[source, go]
----
func (u *GitURL) GetRepositoryName() string
----

GetRepositoryName returns the last element of the Git URL.
Strips the name from any .git extensions in the URL.

.GetNamespace
[source, go]
----
func (u *GitURL) GetNamespace() string
----

GetNamespace returns the middle element(s) of the Git URL.
Depending on the Git hosting service, this name may contain multiple slashes.
Any leading "/" is removed.

.Redacted
[source, go]
----
func (u *GitURL) Redacted() string
----

Redacted returns the same as url.URL:Redacted().

.String
[source, go]
----
func (u *GitURL) String() string
----

String returns the same as url.URL:String().

.GetFullName
[source, go]
----
func (u *GitURL) GetFullName() string
----

GetFullName returns the hostname (or host:port) joined by GetNamespace and GetRepositoryName delimited by slashes.

.AsURL
[source, go]
----
func (u *GitURL) AsURL() *url.URL
----

AsURL converts GitURL to url.URL


'''

=== Values
[source, go]
----
type Values map[string]interface{}
----

Values contain a tree of properties to be consumed by a TemplateEngine.


'''


== Variables


=== ErrInvalidArgument
[source, go]
----
var ErrInvalidArgument = errors.New("invalid argument")
----
ErrInvalidArgument is an error that indicates that a particular field is invalid.


=== ErrKeyNotFound
[source, go]
----
var ErrKeyNotFound = errors.New("key not found")
----
ErrKeyNotFound is an error that indicates that a particular key was not found.


== Functions

=== NewCleanupService
[source, go]
----
func NewCleanupService() *CleanupService
----

















=== NewGitRepository
[source, go]
----
func NewGitRepository(u *GitURL, root Path) *GitRepository
----

NewGitRepository creates a new instance.













=== NewPath
[source, go]
----
func NewPath(elems ...string) Path
----

NewPath constructs a new Path joined by the given elements.
Paths are joined with path.Join.


=== NewFilePath
[source, go]
----
func NewFilePath(elems ...string) Path
----

NewFilePath constructs a new Path joined by the given elements.
Paths are joined with filepath.Join.








=== NewPullRequest
[source, go]
----
func NewPullRequest(
    number *PullRequestNumber, title, body, commitBranch, baseBranch string,
    labels LabelSet,
) (*PullRequest, error)
----

NewPullRequest returns a new instance.
An error is returned if the given properties do not satisfy constraints.











=== NewPullRequestNumber
[source, go]
----
func NewPullRequestNumber(nr *int) *PullRequestNumber
----

NewPullRequestNumber takes the given number and returns a new instance.
If nr is nil, then nil is returned.




=== NewRenderService
[source, go]
----
func NewRenderService(analyticsFactory RenderServiceInstrumentationFactory) *RenderService
----












=== NewTemplate
[source, go]
----
func NewTemplate(relPath Path, perms Permissions) *Template
----

NewTemplate returns a new instance.










=== FromURL
[source, go]
----
func FromURL(url *url.URL) *GitURL
----

FromURL converts the given url.URL into a GitURL.



