= github.com/ccremer/greposync
:kroki-default-format: svg
= package cfg



[source,yaml]
----
include::example$config.yaml[]
----

== Structs

=== Configuration
[source, go]
----
type Configuration struct {
    ProjectRoot    string
    Log            *LogConfig
    PullRequest    *PullRequestConfig
    Template       *TemplateConfig
    Git            *GitConfig
}
----














==== Receivers

===== Sanitize
[source, go]
----
func (config *Configuration) Sanitize()
----

Sanitize does corrective actions on the configuration hierarchy.



=== LogConfig
[source, go]
----
type LogConfig struct {
    Level    string
}
----








=== PullRequestConfig
[source, go]
----
type PullRequestConfig struct {
    Create          bool
    TargetBranch    string
    Labels          []string
    BodyTemplate    string
    Subject         string
}
----




TargetBranch::
TargetBranch is the target remote branch of the pull request.
If left empty, it will target the default branch.

Labels::
Labels is an array of issue labels to apply when creating a pull request.
Labels on existing pull requests are not updated.
It is not validated whether the labels exist, the API may or may not create non-existing labels dynamically.

BodyTemplate::
BodyTemplate is the description used in pull requests.
Supports Go template with the `.Metadata` key.
If this string is a relative path to an existing file in the greposync directory, the file is parsed as a Go template.
If empty, the CommitMessage is used.

Subject::
Subject is the Pull Request title.





=== SyncConfig
[source, go]
----
type SyncConfig struct {
    PullRequest    *PullRequestConfig
    Git            *GitConfig
    Template       *TemplateConfig
}
----












=== GitConfig
[source, go]
----
type GitConfig struct {
    Url              *url.URL
    Dir              string
    SkipReset        bool
    SkipCommit       bool
    SkipPush         bool
    ForcePush        bool
    Amend            bool
    CommitMessage    string
    CommitBranch     string
    DefaultBranch    string
    Name             string
    Namespace        string
}
----


Url::
Url is the full Git URL to the remote repository.
This option is not configurable in `greposync.yml`.
In templates, the URL is looking like ``

Dir::
Dir is the relative path to current working directory where the repository is cloned locally.
This option is not configurable in `greposync.yml`.









Amend::
Amend will amend the last commit.
This option is not configurable in `greposync.yml`.
Configurable only via environment variables or CLI flag.

CommitMessage::
CommitMessage is the string that is passed to `git commit`.
It can contain newlines, for example to pass a long description.



DefaultBranch::
DefaultBranch is the name of the default branch in origin.

Name::
Name is the git repository name without .git extension.

Namespace::
Namespace is the repository owner without the repository name.
This is often a user or organization name in GitHub.com or GitLab.com.





=== TemplateConfig
[source, go]
----
type TemplateConfig struct {
    RootDir    string
}
----


RootDir::
RootDir is the path relative to the current workdir where the template files are located.







