= github.com/ccremer/greposync
:kroki-default-format: svg
= package cfg



[source,yaml]
----
include::example$config.yaml[]
----

== Structs

=== Configuration
[source, go]
----
type Configuration struct {
    Project             *ProjectConfig
    Log                 *LogConfig
    PullRequest         *PullRequestConfig
    Template            *TemplateConfig
    Git                 *GitConfig
    RepositoryLabels    map[string]RepositoryLabel
}
----



















=== ProjectConfig
[source, go]
----
type ProjectConfig struct {
    MainConfigFileName       string
    ConfigDefaultFileName    string
    RootDir                  string
    Jobs                     int
    Include                  string
    Exclude                  string
}
----






RootDir::
RootDir is the local directory where the Git repositories are cloned into.

Jobs::
Jobs is the number of parallel jobs to run.
Requires a minimum of 1, supports a maximum of 8.
1 basically means that jobs are run in sequence.
If this number is 2 or greater, then the logs are buffered and only displayed in case of errors.

Include::
Include is a regex filter that includes repositories only when they match.
The filter is applied to the whole URL.
This option is not configurable in `greposync.yml`.

Exclude::
Exclude is similar to Include, only that matching repository URLs are skipped.
This option is not configurable in `greposync.yml`.





=== LogConfig
[source, go]
----
type LogConfig struct {
    Level    string
}
----








=== PullRequestConfig
[source, go]
----
type PullRequestConfig struct {
    Create          bool
    TargetBranch    string
    Labels          []string
    BodyTemplate    string
    Subject         string
}
----




TargetBranch::
TargetBranch is the target remote branch of the pull request.
If left empty, it will target the default branch.

Labels::
Labels is an array of issue labels to apply when creating a pull request.
Labels on existing pull requests are not updated.
It is not validated whether the labels exist, the API may or may not create non-existing labels dynamically.

BodyTemplate::
BodyTemplate is the description used in pull requests.
Supports Go template with the `.Metadata` key.
If this string is a relative path to an existing file in the greposync directory, the file is parsed as a Go template.
If empty, the CommitMessage is used.

Subject::
Subject is the Pull Request title.





=== RepositoryLabel
[source, go]
----
type RepositoryLabel struct {
    Name           string
    Description    string
    Color          string
    Delete         bool
}
----


Name::
Name is the label name.

Description::
Description is a short description of the label.

Color::
Color is the hexadecimal color code for the label, without the leading #.

Delete::
Delete will remove this label.





=== SyncConfig
[source, go]
----
type SyncConfig struct {
    PullRequest    *PullRequestConfig
    Git            *GitConfig
    Template       *TemplateConfig
}
----












=== GitConfig
[source, go]
----
type GitConfig struct {
    SkipReset        bool
    SkipCommit       bool
    SkipPush         bool
    ForcePush        bool
    Amend            bool
    CommitMessage    string
    CommitBranch     string
    DefaultBranch    string
    Name             string
    Namespace        string
}
----










Amend::
Amend will amend the last commit.
This option is not configurable in `greposync.yml`.
Configurable only via environment variables or CLI flag.

CommitMessage::
CommitMessage is the string that is passed to `git commit`.
It can contain newlines, for example to pass a long description.



DefaultBranch::
DefaultBranch is the name of the default branch in origin.

Name::
Name is the git repository name without .git extension.

Namespace::
Namespace is the repository owner without the repository name.
This is often a user or organization name in GitHub.com or GitLab.com.





=== TemplateConfig
[source, go]
----
type TemplateConfig struct {
    RootDir    string
}
----


RootDir::
RootDir is the path relative to the current workdir where the template files are located.







= package flag



[source,yaml]
----
include::example$config.yaml[]
----

== Structs

=== Cli
[source, go]
----
type Cli struct {
}
----

Cli implements a urfave/cli command line provider.










