= Sync Configuration

There are 2 locations how template variables are configured.

`{defaults-file}` is the config file that defines variables for all managed repositories.
It's expected to be in the current working directory when invoking `gsync`.

`{sync-file}` is the config file that is used to configure individual values per repository.
Each entry extends and potentially overrides variables defined in `{defaults-file}`.
It's expected to be in the root directory of a Git repository.

== Value hierarchy

The following hierarchy of merging and inheriting values is applied.
The last element in the list is overwriting anything defined before.

. `:globals` in `{defaults-file}`
. `directory/` in `{defaults-file}`
. `directory/filename` in `{defaults-file}`
. `:globals` in `{sync-file}`
. `directory/` in `{sync-file}`
. `directory/filename` in `{sync-file}`

.Value hierarchy
[example]
====
.{defaults-file}
[source,yaml]
----
:globals:
  key: 1

dir/:
  key: 2 <1>

dir/subdir/:
  key: 3

dir/subdir/file:
  key: a
----

.{sync-file}
[source,yaml]
----
:globals:
  key: 4

dir/subdir/:
  key: 5

dir/subdir/file:
  key: b <2>
----
<1> Any file within `dir` would get the value `key=2` as there is no override in `{sync-file}`.
<2> The `dir/subdir/file` would get the value `key=b` since it's overriding the key in `{defaults-file}`.
====

[NOTE]
====
* Specifying `/` as the top dir to apply values is not supported.
  Use `:globals` for that purpose.
* Appending the `/` suffix to a directory is necessary, otherwise they are interpreted as files.
====

== Special values

`delete: true`::
When this flag is set, the target file is being deleted.
It is not rendered at all.

[TIP]
====
* Use this flag in `config_defaults.yml` to cleanup files that aren't needed in the managed repositories anymore.
* Use this flag in `.sync.file` to tell greposync to not create certain files.
====

`unmanaged: true`::
If this flag is set, the target file is not modified.

TIP: Use this flag in `.sync.file` if a repository maintains its own version of the file outside of {page-component-name}.

`targetPath: <path>`::
This property can override where the templated file is actually being written to.
It is relative to the Git root directory.

If the path contains the suffix `/`, the directory is changed but the file name is kept.
Any parent directories are created as needed, with `0775` permission flags (before `umask`).

.Special values usage
[example]
====
.`.sync.file`
[source,yaml]
----
.editorconfig:
  unmanaged: true <1>

Makefile:
  delete: true <2>

subdir/.gitignore:
  targetPath: newDir/ <3>
----
<1> The repository keeps its own version of `.editorconfig`.
<2> The repository does not need a `Makefile`.
<3> Parse the template in `subdir/.gitignore`, but write the output to `newDir/.gitignore` in the repository root.
====
