= Go Template

The template or rendering engine is https://golang.org/pkg/text/template/[Go template].
Go template engine can be extended and this allows us to utilize and integrate custom functions.

Sprig::
A library that enhances templates with many utility functions.
Visit the https://masterminds.github.io/sprig/[Sprig function documentation] for reference.

YAML, JSON, TOML::
Additional functions to format data structure into YAML, JSON or TOML.

== The template directory

By default, templates are placed into the `template/` directory.

. Any file is regarded as a template, regardless of file extension.
. The special file `_helpers.tpl` doesn't get created but can host custom template definitions.
. Templates in subdirectories will get the same relative directory structure in the repository.
. 1 occurrence of `.tpl` is removed from the file name, if any.
+
[TIP]
====
This rule exists since some IDEs provide syntax highlighting for Go template and the markup language at the same time if `.tpl` occurrs in the file name.
A file named `README.tpl.md` will become `README.md` in the target repository.
If you actually need a file called `README.tpl.md`, you need to name it `README.tpl.tpl.md`.
====

== Values

Any value defined in `{defaults-file}` and `{sync-file}` are merged and accessible as variable in `.Values`.

.Accessing variables in templates
[example]
====
.{sync-file}
[source,yaml]
----
README.md:
  sections:
    - section 1
----

.README.md.tpl
[source,go]
----
# {{ .Values.sections[0] }}
----
====

NOTE: Inexisting keys will cause an abort for the repository update.

=== Metadata

Each template can use additional metadata fields.
They are exposed in the `.Metadata` field.

.Supported metadata variables
[example]
====
[source]
----
include::example$code/metadata.tpl[]
----
====
