// Code generated by counterfeiter. DO NOT EDIT.
package corefakes

import (
	"sync"

	"github.com/ccremer/greposync/core"
)

type FakeGitRepositoryStore struct {
	FetchGitRepositoriesStub        func() ([]core.GitRepository, error)
	fetchGitRepositoriesMutex       sync.RWMutex
	fetchGitRepositoriesArgsForCall []struct {
	}
	fetchGitRepositoriesReturns struct {
		result1 []core.GitRepository
		result2 error
	}
	fetchGitRepositoriesReturnsOnCall map[int]struct {
		result1 []core.GitRepository
		result2 error
	}
	FetchGitRepositoryStub        func(*core.GitURL) (core.GitRepository, error)
	fetchGitRepositoryMutex       sync.RWMutex
	fetchGitRepositoryArgsForCall []struct {
		arg1 *core.GitURL
	}
	fetchGitRepositoryReturns struct {
		result1 core.GitRepository
		result2 error
	}
	fetchGitRepositoryReturnsOnCall map[int]struct {
		result1 core.GitRepository
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGitRepositoryStore) FetchGitRepositories() ([]core.GitRepository, error) {
	fake.fetchGitRepositoriesMutex.Lock()
	ret, specificReturn := fake.fetchGitRepositoriesReturnsOnCall[len(fake.fetchGitRepositoriesArgsForCall)]
	fake.fetchGitRepositoriesArgsForCall = append(fake.fetchGitRepositoriesArgsForCall, struct {
	}{})
	stub := fake.FetchGitRepositoriesStub
	fakeReturns := fake.fetchGitRepositoriesReturns
	fake.recordInvocation("FetchGitRepositories", []interface{}{})
	fake.fetchGitRepositoriesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitRepositoryStore) FetchGitRepositoriesCallCount() int {
	fake.fetchGitRepositoriesMutex.RLock()
	defer fake.fetchGitRepositoriesMutex.RUnlock()
	return len(fake.fetchGitRepositoriesArgsForCall)
}

func (fake *FakeGitRepositoryStore) FetchGitRepositoriesCalls(stub func() ([]core.GitRepository, error)) {
	fake.fetchGitRepositoriesMutex.Lock()
	defer fake.fetchGitRepositoriesMutex.Unlock()
	fake.FetchGitRepositoriesStub = stub
}

func (fake *FakeGitRepositoryStore) FetchGitRepositoriesReturns(result1 []core.GitRepository, result2 error) {
	fake.fetchGitRepositoriesMutex.Lock()
	defer fake.fetchGitRepositoriesMutex.Unlock()
	fake.FetchGitRepositoriesStub = nil
	fake.fetchGitRepositoriesReturns = struct {
		result1 []core.GitRepository
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRepositoryStore) FetchGitRepositoriesReturnsOnCall(i int, result1 []core.GitRepository, result2 error) {
	fake.fetchGitRepositoriesMutex.Lock()
	defer fake.fetchGitRepositoriesMutex.Unlock()
	fake.FetchGitRepositoriesStub = nil
	if fake.fetchGitRepositoriesReturnsOnCall == nil {
		fake.fetchGitRepositoriesReturnsOnCall = make(map[int]struct {
			result1 []core.GitRepository
			result2 error
		})
	}
	fake.fetchGitRepositoriesReturnsOnCall[i] = struct {
		result1 []core.GitRepository
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRepositoryStore) FetchGitRepository(arg1 *core.GitURL) (core.GitRepository, error) {
	fake.fetchGitRepositoryMutex.Lock()
	ret, specificReturn := fake.fetchGitRepositoryReturnsOnCall[len(fake.fetchGitRepositoryArgsForCall)]
	fake.fetchGitRepositoryArgsForCall = append(fake.fetchGitRepositoryArgsForCall, struct {
		arg1 *core.GitURL
	}{arg1})
	stub := fake.FetchGitRepositoryStub
	fakeReturns := fake.fetchGitRepositoryReturns
	fake.recordInvocation("FetchGitRepository", []interface{}{arg1})
	fake.fetchGitRepositoryMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitRepositoryStore) FetchGitRepositoryCallCount() int {
	fake.fetchGitRepositoryMutex.RLock()
	defer fake.fetchGitRepositoryMutex.RUnlock()
	return len(fake.fetchGitRepositoryArgsForCall)
}

func (fake *FakeGitRepositoryStore) FetchGitRepositoryCalls(stub func(*core.GitURL) (core.GitRepository, error)) {
	fake.fetchGitRepositoryMutex.Lock()
	defer fake.fetchGitRepositoryMutex.Unlock()
	fake.FetchGitRepositoryStub = stub
}

func (fake *FakeGitRepositoryStore) FetchGitRepositoryArgsForCall(i int) *core.GitURL {
	fake.fetchGitRepositoryMutex.RLock()
	defer fake.fetchGitRepositoryMutex.RUnlock()
	argsForCall := fake.fetchGitRepositoryArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitRepositoryStore) FetchGitRepositoryReturns(result1 core.GitRepository, result2 error) {
	fake.fetchGitRepositoryMutex.Lock()
	defer fake.fetchGitRepositoryMutex.Unlock()
	fake.FetchGitRepositoryStub = nil
	fake.fetchGitRepositoryReturns = struct {
		result1 core.GitRepository
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRepositoryStore) FetchGitRepositoryReturnsOnCall(i int, result1 core.GitRepository, result2 error) {
	fake.fetchGitRepositoryMutex.Lock()
	defer fake.fetchGitRepositoryMutex.Unlock()
	fake.FetchGitRepositoryStub = nil
	if fake.fetchGitRepositoryReturnsOnCall == nil {
		fake.fetchGitRepositoryReturnsOnCall = make(map[int]struct {
			result1 core.GitRepository
			result2 error
		})
	}
	fake.fetchGitRepositoryReturnsOnCall[i] = struct {
		result1 core.GitRepository
		result2 error
	}{result1, result2}
}

func (fake *FakeGitRepositoryStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.fetchGitRepositoriesMutex.RLock()
	defer fake.fetchGitRepositoriesMutex.RUnlock()
	fake.fetchGitRepositoryMutex.RLock()
	defer fake.fetchGitRepositoryMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGitRepositoryStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ core.GitRepositoryStore = new(FakeGitRepositoryStore)
